
name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub 저장소 체크아웃
      uses: actions/checkout@v3

    - name: AWS S3에 업로드
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: ./
